# Generated by Django 2.1.7 on 2020-03-19 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_agree'),
    ]

    operations = [
        migrations.AddField(
            model_name='agree',
            name='applicant',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
