# Generated by Django 2.1.7 on 2020-03-19 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='agree',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
