# Generated by Django 2.1.7 on 2020-03-26 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_document_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='doc',
            field=models.FileField(blank=True, null=True, upload_to='upload/files'),
        ),
    ]
