# Generated by Django 2.1.7 on 2020-04-02 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_auto_20200327_0008'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='errormsg',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
